[package]
name = "simple_jwt"
version = "0.9.0"
license = "MIT"
authors = ["realli <lrlanswer@gmail.com>"]
build = "build.rs"
keywords = ["json", "jwt", "web", "token"]
description = "json web token encode/decode"
repository = "https://github.com/realli/simple_jwt"
documentation = "http://realli.github.io/simple_jwt/simple_jwt/"

[features]
default = ["serde_codegen"]
unstable = ["serde_derive"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }

[dependencies]
serde = "0.8"
serde_derive = { version  = "0.8", optional = true }
serde_json = "0.8"
rustc-serialize = "0.3"

[dependencies.openssl]
version = "0.8.3"
features = ["hmac"]

