[package]
name = "simple_jwt"
version = "0.1.0"
authors = ["realli"]

[dependencies]
serde = "0.8"
serde_macros = "0.8"
serde_json = "0.8"
rustc-serialize = "0.3"

[dependencies.openssl]
version = "0.8.3"
features = ["hmac"]

